
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these values with your new Supabase account credentials
const SUPABASE_URL = "https://hpgznuodqauaggsasdww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZ3pudW9kcWF1YWdnc2FzZHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTQ1NzUsImV4cCI6MjA1NjY3MDU3NX0.r3PYhVliDALVm1Cd3_PAK40wwAdSNEhrIi5hrSOP5G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
