
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Replace these values with your new Supabase account credentials
const SUPABASE_URL = "https://gknlawknjskmjwlfgopf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrbmxhd2tuanNrbWp3bGZnb3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MDY3NjYsImV4cCI6MjA1NTA4Mjc2Nn0.7kmddS46E85aaWQ0OGeYN3MrTK58XocKoNF8S1M58gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
